version: "3.8"
services:
  app:
    build: .
    ports:
      - "2003:8081"
    volumes:
      - .:/app
    stdin_open: true
    tty: true

networks:
  default:
    external:
      name: network-production
