services:
  inpalm-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inpalm-frontend-production
    image: inpalm-frontend:production
    ports:
      - "2003:80"

networks:
  default:
    external:
      name: network-production