export const REACT_APP_BASE_URL = "http://142.93.247.73";

export const REACT_APP_OMNIAUTH_PORT = "4001";
export const REACT_APP_BACKEND_PORT = "4002";

export const REACT_APP_OMNIAUTH_URL = `${REACT_APP_BASE_URL}:${REACT_APP_OMNIAUTH_PORT}`;
export const REACT_APP_BACKEND_URL = `${REACT_APP_BASE_URL}:${REACT_APP_BACKEND_PORT}`;
