export const componentStyle = {
  card: {
    backgroundColor: "#fff",
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    elevation: 3,
  },
  cardContainer: { flexDirection: "row", marginBottom: 5 },
  cardContainerName: { fontSize: 16, fontWeight: "bold", marginRight: 5 },
  cardContainerValue: { fontSize: 16 },
  container: {
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  containerBgColor: { backgroundColor: "#f5f5f5" },
  imgBanner: {
    height: 120,
    marginBottom: 20,
    width: 250,
  },
  inlineContainer: { flexDirection: "row", marginTop: 10 },  
  inputLogin: {
    backgroundColor: "#fff",
    borderColor: "#ccc",
    borderRadius: 8,
    borderWidth: 1,
    fontSize: 16,
    height: 50,
    marginBottom: 15,
    paddingLeft: 10,
    width: "100%",
  },
  inputFilter: {
    backgroundColor: "#fff",
    borderColor: "#ccc",
    borderRadius: 8,
    borderWidth: 1,
    height: 40,
    marginBottom: 10,
    paddingHorizontal: 10,
  },
  textTitle: {
    fontSize: 22,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 20,
  },
};
