const portuguese = {
  FAILURE: {
    INVALID_DATETIME: "Campo deve ser uma data-hora.",
    INVALID_EMAIL: "Campo deve ser um e-mail válido.",
    INVALID_NUMBER: "Campo deve ser um número.",
    MANDATORY_FIELD: "Campo obrigatório.",
    PASSWORD_MISMATCH: "A senha e a confirmação não correspondem. Por favor, corrija.",
    SOMETHING_WRONG: "Algo deu errado!",
    UNSELECTED_RECORD: "Ops! Você não selecionou nenhum registro para remover. Escolha pelo menos um 😉",
  },
  INFO: {
    ACTUAL_LENGTH: "Comprimento Constatado",
    ACTUAL_WIDTH: "Largura Constatada",
    ADD: "Adicionar",
    ADJUSTMENT_LENGTH: "Comprimento para Ajuste",
    ADJUSTMENT_WIDTH: "Largura para Ajuste",
    ALLOW: "Permitir",
    ASSEMBLY_TEAM: "Equipe de Montagem",
    CANCEL: "Cancelar",
    CHECKLIST: "Checklist",
    CHECKLISTS: "Checklists",
    CONFIRM_PASSWORD: "Confirmação de Senha",
    CONFIRM_REMOVAL: "Você deseja remover este registro? Esta operação não pode ser desfeita!",
    CUSTOMER: "Cliente",
    DEFAULT_POLICY: "Política Padrão",
    DELIVERY_RESPONSIBLE_PNC: "Responsável pela Entrega PNC",
    DENY: "Negar",
    DESCRIPTION: "Descrição",
    EDIT: "Editar",
    EMAIL: "E-mail",
    EMPTY: "Vazio!",
    ENVIRONMENTS: "Ambientes",
    ESTIMATED_DELIVERY_DATE: "Data Prevista de Entrega",
    FILTER: "Filtrar",
    FINISHED_AT: "Fim",
    INSPECTED_BY: "Inspetor de Qualidade",
    HOME: "Home",
    NAME: "Nome",
    NOTE: "Observação",
    PASSWORD: "Senha",
    PHOTO: "Foto",
    PIECE_PENDINGS: "Pendências de Peça",
    PIECE_PENDING_NOTES: "Observações de Pendência de Peça",
    PIECE_PENDINGS_SHORT: "Pend. de Peça",    
    PLACEHOLDER: (fieldName: string) => `Forneça o campo ${fieldName}`,
    PROJECT_CODE: "Código do Projeto",
    POLICY_EXCEPTIONS: "Exceções de Política",
    PURCHASE_PENDINGS: "Pendências de Compra",
    PURCHASE_PENDING_NOTES: "Observações de Pendência de Compra",
    PURCHASE_PENDINGS_SHORT: "Pend. de Compra",
    QUANTITY: "Quantidade",
    REMOVE: "Remover",
    RESOURCES: "Recursos",
    ROLE: "Papel",
    ROLES: "Papéis",
    SAVE: "Salvar",
    STARTED_AT: "Início",
    TECHNICAL_REPORTS: "Parecer Técnico",
    THICKNESS: "Espessura",
    USER: "Usuário",
    USERS: "Usuários",
  }
};

export const defaultLanguage = portuguese;